// Builds the static site that Netlify serves from v10/.
//   source : src/index.src.html   (the only file to edit — React app inside <script type="text/babel">)
//   output : v10/index.html        (generated — do not edit by hand)
//            v10/app.<hash>.js     (JSX compiled ahead of time; hash busts browser caches)
//            v10/vendor/*.js       (pinned React / ReactDOM / supabase-js copies, committed — no CDN at runtime)
// Usage: node tools/build.mjs [--check]   (--check: exit 1 if v10/ is out of date with src/, write nothing)
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformSync } from 'esbuild';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src', 'index.src.html');
const OUT = join(ROOT, 'v10');
const CHECK = process.argv.includes('--check');

// CDN script tags in the source → pinned local copies. Babel standalone is dropped entirely.
const VENDOR = [
  [/<script[^>]*src="https:\/\/unpkg\.com\/react@18[^"]*"[^>]*><\/script>/, 'vendor/react-18.3.1.production.min.js'],
  [/<script[^>]*src="https:\/\/unpkg\.com\/react-dom@18[^"]*"[^>]*><\/script>/, 'vendor/react-dom-18.3.1.production.min.js'],
  [/<script[^>]*src="https:\/\/cdn\.jsdelivr\.net\/npm\/@supabase\/supabase-js@2[^"]*"[^>]*><\/script>/, 'vendor/supabase-js-2.117.2.umd.js'],
];
const BABEL_TAG = /\s*<script[^>]*src="https:\/\/unpkg\.com\/@babel\/standalone[^"]*"[^>]*><\/script>/;

const fail = (msg) => { console.error('build: ' + msg); process.exit(1); };
let html = readFileSync(SRC, 'utf8');

const blocks = [...html.matchAll(/<script type="text\/babel">([\s\S]*?)<\/script>/g)];
if (blocks.length !== 1) fail(`expected exactly 1 <script type="text/babel"> block in src, found ${blocks.length}`);

// format 'iife': the app's top-level `const supabase` etc. must not collide with the `var supabase` global that the
// supabase-js UMD bundle declares (in-browser Babel used to turn const into var, which hid the clash).
let js;
try {
  js = transformSync(blocks[0][1], { loader: 'jsx', jsx: 'transform', format: 'iife', minify: true, target: 'es2019', legalComments: 'none' }).code;
} catch (e) {
  fail('JSX does not compile:\n' + (e.errors || []).map(er => `  ${er.text} @ src line ${er.location ? er.location.line + html.slice(0, blocks[0].index).split('\n').length - 1 : '?'}`).join('\n'));
}
const hash = createHash('sha256').update(js).digest('hex').slice(0, 10);
const appFile = `app.${hash}.js`;

if (!BABEL_TAG.test(html)) fail('babel standalone <script> not found in src (layout changed?)');
html = html.replace(BABEL_TAG, '');
for (const [re, local] of VENDOR) {
  if (!re.test(html)) fail(`CDN tag for ${local} not found in src`);
  html = html.replace(re, `<script src="${local}"></script>`);
}
html = html.replace(blocks[0][0], () => `<script src="${appFile}"></script>`);
html = html.replace(/<head>/i, '<head>\n  <!-- GENERATED by tools/build.mjs from src/index.src.html — edit the source, then run ./build.sh -->');
if (/unpkg\.com|cdn\.jsdelivr\.net|text\/babel/.test(html)) fail('built HTML still references a CDN script or text/babel');

const builtNow = { 'index.html': html, [appFile]: js };
if (CHECK) {
  const stale = Object.entries(builtNow).filter(([f, content]) => { try { return readFileSync(join(OUT, f), 'utf8') !== content; } catch (e) { return true; } }).map(([f]) => f);
  if (stale.length) fail(`v10/ is out of date with src/ (${stale.join(', ')}) — run ./build.sh and commit`);
  console.log(`build --check: v10/ is up to date (${appFile})`);
  process.exit(0);
}
for (const f of readdirSync(OUT)) if (/^app\.[0-9a-f]{10}\.js$/.test(f) && f !== appFile) unlinkSync(join(OUT, f));
writeFileSync(join(OUT, appFile), js);
writeFileSync(join(OUT, 'index.html'), html);
console.log(`built v10/index.html + v10/${appFile} (${Math.round(js.length / 1024)} KB, was ${Math.round(blocks[0][1].length / 1024)} KB of JSX compiled in the browser)`);
